spring:
  application:
    name: FinTrack
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${OAUTH_GOOGLE_CLIENT_ID:default-client-id}
            client-secret: ${OAUTH_GOOGLE_CLIENT_SECRET:default-client-secret}
            scope:
              - email
              - profile
  cache:
    type: redis # 이걸 빼면 캐시가 SimpleCache (기본 Map 기반)으로 동작할 수도 있으니까 꼭 명시
  data:
    redis:
      host: localhost
      port: 6379
      timeout: 6000 # 6초 읽기 타임아웃
      client-type: lettuce # 기본값이 lettuce (Jedis도 가능)



logging:
  level:
    org.springdoc: TRACE

jwt:
  secret: 7dGYq3vKvMSxYhoDwrrBsESJwkPDwT8NsYctLQKzd/Q=
  expiration-ms: 3600000